### ISSUE TITLE
Right Click Issue

### ISSUE THREAD

**Issue by David-Carty** [UnrealSecurity/context-js#1]
If the context menu is open and the user right-clicks again then I would expect any subsequent right-click to be ignored if the user is hovering over the menu.  This is not the case: https://heapoverride.sexy/contextjs/

**Comment by heapoverride** [comment]
Took me a while to realize what you meant. So when you right-click over the menu it should not respawn the menu in the new location, right? Shouldn't be too hard to add this. I will look into it after couple days.
Thanks & happy upcoming new year!

**Comment by David-Carty** [comment]
It's a really neat component. All the best D.
